name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js for Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'  # Matches your specified Node version

    # Install Frontend Dependencies
    - name: Install Dependencies
      run: npm install  # Removed working-directory, assuming root

    # Build Frontend
    - name: Build Frontend
      run: npm run build  # Removed working-directory, assuming root

    # Deploy to VPS
    - name: Deploy to VPS
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        FRONTEND_PATH: ${{ secrets.APP_PATH }}  # Adjust to your deployment path
      run: |
        # Install SSH key
        echo "$VPS_SSH_KEY" > deploy_key
        chmod 600 deploy_key

        # Deploy Frontend
        rsync -avz --delete -e "ssh -i deploy_key -o StrictHostKeyChecking=no" \
          ./dist/ $VPS_USER@$VPS_HOST:$FRONTEND_PATH  # Adjusted path to ./dist/

        # Restart Nginx on VPS
        ssh -i deploy_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
          sudo systemctl restart nginx
        EOF

        # Clean up
        rm deploy_key
